"""Report Writer Agent — Kimi K2.6 + TokenRouter Integration.

Generates comprehensive audit reports using Kimi K2.6's long-context
capabilities, routed through TokenRouter for optimal model selection.
"""

import time

from src.identity.terminal3 import identity, ProofEntry
from src.routing.router import router


REPORT_SYSTEM_PROMPT = """You are an expert compliance auditor generating a formal audit report.
Given company data and risk scores, produce a structured Markdown audit report that includes:
1. Executive Summary
2. Data Sources & Methodology
3. Risk Assessment (with scores and explanations)
4. Key Findings
5. Recommendations
6. Appendix (data provenance)

Be precise, professional, and factual. Reference specific data points from the provided information."""


class ReportWriterAgent:
    """Agent that generates audit reports via Kimi K2.6."""

    AGENT_ROLE = "report_writer"

    async def write_report(
        self,
        company_name: str,
        collected_data: dict,
        risk_data: dict,
        proof_chain_so_far: list[dict],
    ) -> tuple[str, ProofEntry]:
        """Generate the final audit report.

        Args:
            company_name: Name of the audited company.
            collected_data: Output from Data Collector.
            risk_data: Output from Risk Scorer.
            proof_chain_so_far: Proof entries from previous agents.

        Returns:
            Tuple of (report markdown string, signed proof entry).
        """
        input_data = {
            "company_name": company_name,
            "data_sources": collected_data.get("sources_count", 0),
            "risk_level": risk_data.get("scores", {}).get("risk_level", "UNKNOWN"),
        }

        # Build the prompt with all context
        user_message = self._build_prompt(company_name, collected_data, risk_data, proof_chain_so_far)

        # Generate report via Kimi K2.6 (through TokenRouter)
        report = await self._generate_report(user_message)

        output_data = {
            "company_name": company_name,
            "report_length": len(report),
            "generated_at": time.time(),
        }

        # Sign the action with Terminal 3
        proof = await identity.sign_action(
            agent_role=self.AGENT_ROLE,
            action="generate_audit_report",
            input_data=input_data,
            output_data=output_data,
        )

        return report, proof

    def _build_prompt(
        self,
        company_name: str,
        collected_data: dict,
        risk_data: dict,
        proof_chain: list[dict],
    ) -> str:
        """Build the prompt for report generation."""
        return f"""Generate a compliance audit report for **{company_name}**.

## Collected Data

### Company Filings
{self._format_items(collected_data.get('filings', []))}

### Recent News
{self._format_items(collected_data.get('news', []))}

## Risk Scores
- Financial Health: {risk_data.get('scores', {}).get('financial_health', {}).get('score', 'N/A')}/100
  - {risk_data.get('scores', {}).get('financial_health', {}).get('explanation', '')}
- Regulatory Compliance: {risk_data.get('scores', {}).get('regulatory_compliance', {}).get('score', 'N/A')}/100
  - {risk_data.get('scores', {}).get('regulatory_compliance', {}).get('explanation', '')}
- Reputation Risk: {risk_data.get('scores', {}).get('reputation_risk', {}).get('score', 'N/A')}/100
  - {risk_data.get('scores', {}).get('reputation_risk', {}).get('explanation', '')}
- Composite Score: {risk_data.get('scores', {}).get('composite_score', 'N/A')}
- Overall Risk Level: {risk_data.get('scores', {}).get('risk_level', 'UNKNOWN')}

## Audit Trail
This report was generated by a pipeline of {len(proof_chain)} verified agents.
Each step is signed using TEE (Trusted Execution Environment) for tamper-proof verification.

Generate the full audit report now."""

    def _format_items(self, items: list[dict]) -> str:
        """Format a list of data items for the prompt."""
        if not items:
            return "No data available."
        lines = []
        for item in items:
            title = item.get("title", "Untitled")
            source = item.get("source", "Unknown")
            summary = item.get("summary", "")
            date = item.get("date", "")
            lines.append(f"- [{title}] (Source: {source}, Date: {date})\n  {summary}")
        return "\n".join(lines)

    async def _generate_report(self, user_message: str) -> str:
        """Generate report via Kimi K2.6 through TokenRouter.

        Falls back to a template if API is unavailable.
        """
        try:
            messages = [
                {"role": "system", "content": REPORT_SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ]
            return await router.route_to_kimi(messages, max_tokens=8192)
        except Exception as e:
            # Fallback: generate a template report
            # This ensures the demo works even if the API is temporarily down
            return self._fallback_report(user_message, str(e))

    def _fallback_report(self, context: str, error: str) -> str:
        """Generate a fallback template report when API is unavailable."""
        return f"""# Compliance Audit Report

> ⚠️ Generated using fallback template (API error: {error})

## Executive Summary
This audit was conducted using AuditForge's multi-agent pipeline with verifiable agent identities.

## Methodology
- Data Collection: Bright Data web scraping (company filings + news)
- Risk Scoring: Isolated computation in Daytona sandbox
- Report Generation: Kimi K2.6 long-context analysis (fallback mode)
- Verification: Terminal 3 TEE-signed proof chain

## Context Provided
{context[:2000]}

---
*Report generated by AuditForge Report Writer Agent*
*All agent actions are cryptographically signed and verifiable*
"""
